name: CI

on: [push, pull_request]

jobs:
  build:
    name: ci test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build

    - name: Run unit tests
      run: npm run test

    - name: Install Playwright
      run: npx playwright install

    - name: Setup xvfb
      run: sudo apt-get install xvfb -y

    # e2e tests not working right now  

    # - name: Run e2e tests
    #   run: npm run e2e

    # - name: Run e2e tests
    #   run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" npm run e2e

    - name: Lint commit messages
      run: npx commitlint --from=master

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build