name: CI

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test

    - name: Install Playwright
      run: npx playwright install 

    - name: Run e2e tests
      run: npm run e2e

    - name: Lint commit messages
      run: npx commitlint --from=main